### ISSUE TITLE
Cannot package native image

### ISSUE THREAD

**Issue by kdnakt** [kdnakt/quarkus-sandbox#1]
```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing io.quarkus.dynamodb.runtime.DynamodbClientProducer.createUrlConnectionClientBuilder(DynamodbClientProducer.java:118)
Call path from entry point to io.quarkus.dynamodb.runtime.DynamodbClientProducer.createUrlConnectionClientBuilder(SyncHttpClientConfig): 
        at io.quarkus.dynamodb.runtime.DynamodbClientProducer.createUrlConnectionClientBuilder(DynamodbClientProducer.java:118)
        at io.quarkus.dynamodb.runtime.DynamodbClientProducer.initHttpClient(DynamodbClientProducer.java:109)
        at io.quarkus.dynamodb.runtime.DynamodbClientProducer.client(DynamodbClientProducer.java:49)
        at io.quarkus.dynamodb.runtime.DynamodbRecorder.createClient(DynamodbRecorder.java:23)
        at io.quarkus.deployment.steps.DynamodbProcessor$buildClients18.deploy_0(DynamodbProcessor$buildClients18.zig:79)
        at io.quarkus.deployment.steps.DynamodbProcessor$buildClients18.deploy(DynamodbProcessor$buildClients18.zig:128)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:180)
        at io.quarkus.runtime.Application.start(Application.java:94)
        at io.quarkus.runtime.Application.run(Application.java:218)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
        ... 7 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:238)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:193)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:219)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:182)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1571)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1546)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5125)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        ... 4 more
Error: Image build request failed with exit status 1
```

**Comment by kdnakt** [comment]
Fixed in b8f30e9fbc267b38c6790ce1476bfc16af8a9f7e
